export const ConstantValues = {
  // https://instaccess.co.za/instaccess_backend/index.php/api/users?id=19
  // COMPANY_ID_STR:"69",
  COMPANY_ID_STR: "75",
  BASE_API_URL: "https://instaccess.co.za/instaccess_backend/index.php/api/",
  URL_USER_REGISTER: "user/register",
  URL_USER_LOGIN: "user/login",
  USERS_STR: "users",
  URL_LOGOUT: "users/logout",
  URL_COUNTRYIS: "countries",
  URL_STATES: "states",
  URL_CITYS: "cities",
  URL_LOCATIONS: "locations",
  URL_COMANIES: "companies",
  URL_SYSTEM_QUESTIONS: "SystemQuestions",
  URL_COMPANY_QUESTIONS: "CompanyQuestions",
  URL_CREATE_SYSTEM_QUESTIONS: "SystemQuestionsSubmissions/create",
  URL_ACTIVITIES: "activities",
  URL_FAVRITE_LOCATION: "location/update/",
  URL_LOCATION_CREATE: "location/create",
  URL_API_CHANGE_PASSWORD: 'user/changePassword',
  URL_CHECKOUT: "activity/update/",
  URL_ACTIVITY_CREATE: "activity/create",
  URL_WRONG_QUESTIONS: "activity/getWrongQuestions",
  URL_NOTES: "notes",
  URL_UPDATE_NOTE: "note/update/",
  URL_NOTE_CREATE: "note/create",
  URL_TRIGGER_QUESTIONS: "NonAppUsers/fetchTriggerQuestions",
  URL_LOCATION_SETTINGS: "LocationSettings",
  URL_DIVISIONS: "divisions",
  URL_NONAPP_USER_CREATE: "NonAppUsers/create",
  URL_NON_APP_USER_SUBMITQUESTIONS: "SystemQuestionsSubmissionsController/create",
  URL_NON_APP_USER_GET_FETCHING_SYSTEMQUESTIONS: "NonAppUsersController/fetchScreeningQuestions",
  URL_USER_UPDATE: "user/update/",
  URL_REFERENCES: "references",
  URL_DEPARTMENTS: "departments",
  URL_FORGOT_PASSWORD_STR: "user/forgotPassword",
  URL_CREATE_GEO_ADDRESS: "location/getCityStateCountryids",
  URL_FORMS: "forms",
  URL_FORM_QUESTIONS: "formQuestions",
  URL_PURPOSE_OF_VISIT: "purposeVisiting",
  URL_SCAN_OUT: "gateActivity/scanOut",
  URL_CAPACITY_STR: "Capacity",
  URL_CREATE_GATE_ACTIVITY: "gateActivity/create",
  URL_UPDATE_GATE_ACTIVITY: "gateActivity/update/",
  URL_DELETE_GATE_ACTIVITY: "gateActivity/delete/",
  URL_GET_GATE_ACTIVITIES: "gateActivities",
  URL_FORM_SUBMISSION_STR: "formSubmission/create",
  URL_FORM_SUBMISSION_ANSWER_STR: "formSubmissionAnswer/create",
  URL_LOYALTY_CARDS_STR: "loyaltyCards",
  URL_LOYALTY_CARD_CREATE_STR: "loyaltyCard/create",
  URL_LOYALTY_CARD_DELETE_STR: "loyaltyCard/delete/",
  URL_LOYALTY_CARD_UPDATE_STR: "loyaltyCard/update/",
  URL_WHITE_LABEL_SETTINGS_STR: "whitelabelSettings",
  FORGOT_EMAIL_TITLE_STR: 'Your password reset email has been sent!',
  USER_TYPE_PERSONAL_STR: "Personal",
  USER_TYPE_ADMIN_STR: "Admin",
  // USER_TYPE_SUPER_ADMIN_STR: "super_admin",
  USER_TYPE_SUPER_ADMIN_STR: "Super Admin",
  USER_TYPE_ADMIN_DEVICE_STR: "Admin Device",
  USER_TYPE_GATE_DEVICE_STR: "Gate Device",
  USER_TYPE_EMPLOYEE_STR: "Employee",
  USER_TYPE_MEMBER_STR: "Member",
  PERSONAL_STR: "Personal",
  BUSSINESS_STR: "Business",
  FIRSTNAME_STR: "FIRST NAME",
  LAST_NAME_STR: "LAST NAME",
  MOBILE_NUMBER_STRING: "MOBILE NUMBER",
  ADD_NOTE: "Add Note",
  EMAIL_STR: "EMAIL",
  PASSWORD_STR: "PASSWORD",
  CONFIRM_PASSWORD_STR: "CONFIRM PASSWORD",
  CREATE_ACCOUNT_STR: "CREATE ACCOUNT",
  ALREADY_HAVE_AN_ACCOUNT_STR: "Already have an account?",
  LOGIN_HERE_STR: "Login Here",
  COMPANY_STR: "COMPANY",
  FIRSTNAME_ADMIN_STR: "FIRST NAME(ADMIN)",
  LASTNAME_ADMIN_STR: "LAST NAME(ADMIN)",
  LAND_LINE_STR: "LANDLINE",
  CELL_NUMBER_STR: "CELL NUMBER",
  ADDRESS_STR: "ADDRESS",
  HOME_LOCATION_STR: "Home Location",
  CLICK_HERE_GET_GEO_ADDRESS: "Click to Geo Locate Address",
  CITY_STR: "CITY",
  STATE_STR: "STATE",
  COUNTRY_STR: "COUNTRY",
  POSTAL_CODE_STR: "POSTAL CODE",
  LOGIN_STR: "SIGN IN",
  DONT_HAVE_AN_ACCOUNT_STR: "Don't have an account",
  CREATE_ACCOUNT_STR_SMALL: "Create Account",
  FORGOT_PASSWORD_STR: "Forgot Password",
  HOME_STR: "Home",
  CHECKIN_STR: "Check In",
  EMPLOYEE_STR: "Employee",
  PROFILE_STR: "Profile",
  CLUB_STR: "Club",
  FLASH_CLUB_STR: "Flash Club",
  DASHBOARD_STR: "Dashboard",
  SUBMISSIONS_STR: "Submissions",
  REWORDS_STR: "Rewards",
  MORE_STR: "More",
  MAIN_GATE_STR: "Geo Rep Main Gate",
  SERACH_STR: " ",
  BUSSINESS_CENTER_STR: "The Business Centre",
  PERSONAL_DETAILS_SHARED_STR: "PERSONAL DETAILS SHARED",
  YES_STR: "Yes",
  NO_STR: "No",
  PERSON_VISIT_STR: "PERSON VISITING",
  INSERT_TEMARATURE_STR: "INSERT TEMPERATURE",
  PLEASE_SIGN_BELOW_STR: "PLEASE SIGN BELOW",
  SCREENING_QUESTIONS_STR: "SCREENING QUESTIONS",
  ARE_YOU_WEARING_A_PROTECTIVE_MASK_STR: "ARE YOU WEARING A PROTECTIVE FACE MASK?",
  SUBMIT_STR: "REQUEST ENTRY",
  FORM_QUESTIONS_SUBMIT_STR: "SUBMIT",
  SELECT_DATE_STR: "Select Date",
  ACCESS_DENIED_STR: "Access Denied",
  CLOSE_STR: "CLOSE",
  PLEASE_SPEAK_SECURITY_OFFICER: "Please speak to security officer",
  OR_RECEPTION_FORTHER_INFORMATION_STR: "or reception for further information",
  OR_RECEPTION_TO_GAIN_ACCESS_STR: "or reception to gain access",
  ACCESS_PENDING_STR: "Access Pending",
  ACCESS_APPROVED_STR: "Access Approved",
  VISITER_ARAIVAL_STR: "Visitor Arraival",
  EXIT_APPROVED_STR: "Exit Approved",
  SEARCH_NAME_STRING: "Locations",
  VISITOR_ARRAIVAL_STR: "Visitor Arrival",
  APPROVED_FOR_ACCESS_WAITING_STR: "have been approved for access and waiting for you at reception",
  SEND_RESPONSE_STR: "SEND RESPONSE",
  SEND_STR: "Send",
  USE_MY_DIGITAL_SIGNATURE_STR: "Use My Digital Signature",
  ACCESS_CONTROL_STR: "Access Control",
  NEW_MESSAGE_STR: "New Message",
  APPROVE_STR: "Approve",
  REJECTED_STR: "Reject",
  COMMENT_STR: "Comment",
  ID_NUMBER_STR: "ID Number",
  ACCESS_STR: "Access",
  COMES_FROM_STR: "Comes from",
  EMAIL_STR_S: "Email",
  MOBILE_NUMBER_STR_S: "Mobile Number",
  STREET_ADDRESS_STR: "Street Address",
  CITY_STR_S: "City",
  STATE_OR_PROVENCE_STR: "State/Province",
  COUNTRY_STR_S: "Country",
  STATE_STR_S: "State",
  ZIP_OR_POSTCODE_STR: "Zip/Postcode",
  SHARING_PREFERENCES_STR: "Information Sharing Preferences",
  NOTIFICATIONS_STR: "Notifications",
  HOME_OFFICE_STR: "Home Office",
  HOME_OFFICE_NAME_STR: "Home Office Name",
  HOME_OFFICE_INFORMATION: "Home Office Information",
  ENABLE_ACCESS_CONTROL_NOTIFICATIONS_STR: "Enable Access Control Notifications",
  SHARE_EMAIL_STR: "Share Email",
  SHARE_ID_NUMBER_STR: "Share ID Number",
  SHARE_ADDRESS_STR: "Share Address",
  SHARE_PROFILE_PHOTO_STR: "Share Profile Photo",
  DIGITAL_SIGNATURE_STR: "Digital Signature",
  DELETE_STR: "Delete",
  ADD_STR: "ADD",
  ADD_NEW_STR: "Add New",
  EDIT_PROFILE_STR: "EDIT PROFILE",
  FILES_STR: "Files",
  YOU_ARE_APPROVED_FOR_ACCESS_STR: "You are approved for access",
  CHECKOUT_STR: "CHECKOUT",
  CHECK_IN_FOR_STR: "CHECKED IN FOR",
  HOURS_STR: "HOURS",
  CURRENT_LOCATION_STR: "Current Location",
  MIN_STR: "MIN",
  SECS_STR: "SEC",
  LEAVE_A_NOTE_STR: "Leave a note",
  LEAVE_A_REVIEW_STR: "Leave a review",
  RATE_YOUR_EXPERIENCE: "Rate your experience",
  DESCRIBE_YOUR_EXPERIENCE_STR: "Describe your experience",
  SAVE_STR: "SAVE",
  SMALL_SAVE_STR: "Save",
  WELCOME_CRAIGE_LIST_STR: "Welcome ",
  EMPLOYEE_ENTRY_STR: "EMPLOYEE ENTRY",
  VISITOR_ENTRY_STR: "VISITOR ENTRY",
  EMPLOYEE_NUMBER_STR: "Employee Number",
  EMPLOYEECODE_OR_IDNUMBER: "Employee Code / ID / Email",
  HOME_CHOICE_WYNBERG_RECEPTION: "Homechoice Wynberg Reception",
  WHERE_DID_YOU_TRAVEL_FROM_STR: "WHERE DID YOU TRAVEL FROM?",
  WHERE_WERE_YOU_STR: "WHERE WERE YOU",
  DATE_DEPARTED_STR: "DATE DEPARTED",
  DATE_RETURNED_STR: "DATE RETURNED",
  DATE_OF_THE_TEST_STR: "DATE OF THE TEST",
  SELECT_DATE_STR: "Select Date",
  EMPLOYEE_CODE_STR: "EMPLOYEE CODE",
  EMAIL_ADDRESS_STR: "EMAIL ADDRESS",
  USER_CREATED_SUCCESS_ALERT_STR: "User created successfully",
  OK_ALERT_STR: "OK",
  USER_CREATED_FAILED_ALERT_STR: "User created failed",
  INVALID_LOGIN_CREDENTIALS_ALERT_STR: "Invalid login credentials",
  ENTER_EMAIL_ADDRESS_ALERT: 'Please enter email address',
  ENTER_VALID_EMAIL_ADDRESS_ALERT: 'Please enter valid email address',
  ENTER_PASSWORD_ALERT: 'Please enter password',
  PASSWORD_LENGTH_ALERT: 'Password must be more than 5 letter',
  SCAN_QR_STR: "SCAN",
  QR_STR: "QR",
  SELECT_COUNTRY_STR: "Select Country",
  SELECT_STATE_STR: "Select State",
  SELECT_CITY_STR: "Select City",
  CONFIRM_CLOSE_APP_ALERT_STR: 'Do you want to quit the app?',
  CANCEL_STR: 'Cancel',
  STOP_SCAN_STR: "Stop Scan",
  PLEASE_WAIT_GETINGLOCTAION: "Please Wait Getting Location",
  GETTING_LOCATION_STR: "Loading Current Location address",
  LOADING_STR: "Loading...",
  PLEASE_WAIT_STR: "Please wait..",
  LOGOUT_STR: "Logout",
  PLEASE_ENTER_EMPLOYEE_NUMBER_STR: "Please enter employee number",
  PLEASE_ENTER_VISITOR_STR: "Please enter visitor number",
  APPROVED_SMALL_STR: "approved",
  DENIED_SMALL_STR: "denied",
  PENDING_SMALL_STR: "pending",
  ONSITE_STR: "Onsite",
  YOU_ARE_ALREADY_CHECKED_IN_OTHER_LOCATION_STR: "You are already checked into another location. Please Check out before trying to access a new location",
  COMPANY_NAME_STR: "Company",
  DIVISION_NAME_STR: "Division",
  DEPARTMENT_NAME_STR: "Department",
  LOCATION_NAME_STR: "Location",
  CELL_NUMBER_SMALL_STR: "Cell Number",
  EMAIL_ADDRESS_SMALL_STR: "Email Address",
  ADDRESS_SMALL_STR: "Address",
  DIGITAL_SIGNATURE_ADDED_SUCCESSFULLY: "Signature Added Successfully",
  EDIT_PROFILE_SUCCESSFULLY_STR: "Edit Profile Successfully",
  SAVED_SUCCESSFULLY_STR: "Save Details Successfully",
  FORM_SUBMITED_SUCCESSFULLY_STR: "Form Successfully Submitted",
  RESET_PASSWORD_STR: "Reset Password",
  RESET_YOUR_PASSWORD_STR: "Reset Your Password",
  FORGOT_PASSWORD_STR: "Forgot Password",
  LEAVE_ANOTE_SAVEALERT_STR: "Note Saved Successfully",
  LEAVE_AREVIEW_SAVEALERT_STR: "Review Saved Successfully",
  CHANGEPASSWORD_STR: "Change Password",
  CURRENT_PASSWORD_PLACEHOLDER_NAME: 'Current Password',
  NEW_PASSWORD_PLACEHOLDER_NAME: 'New Password',
  CONFIRM_PASSWORD_PLACEHOLDER_NAME: 'Confirm Password',
  ALERT_MESSAGE_FOR_ENTER_CURRENTPASSWORD: 'please enter current password',
  ALERT_MESSAGE_FOR_ENTER_NEW_PASSWORD: 'please enter new password',
  ALERT_MESSAGE_FOR_ENTERCONFIRM_PASSWORD: 'please enter confirm password',
  ALERT_MESSAGE_FOR_CHECKPASSWORDLENGTH: 'password  must be more than 5',
  ALERT_MESSAGE_FOR_CURRENT_PASSWORD_NOT_MATCHED_WITH_NEW_PASSWORD: 'new password is not matched with confirm password',
  ALERT_MESSAGE_TITLE_PASSWORDCHANGE_SUCCSESS: 'Your Password Changed Successfully',
  ALERT_PLEASE_ENTER_VALID_CURRENTPASSWORD_STR: "Please Enter Valid Current Password",
  SELECTED_STR: "Selected",
  NO_DATA_FOUND_STR: "No Data Found",
  SCANQR_STR: "Scan Code",
  INSER_TEXT_STR: "Insert Text",
  ENTRY_QUESTIONS_ARE_SET_FOR_LOCATION_STANDARDS: "Entry questions are set per the location's standards",
  REFERENCES_STR: "Covid - 19 References",
  UPLOAD_FRONT_CARD_STR: "Upload Front Card",
  UPLOAD_BACK_CARD_STR: "Upload Back Card",
  SELECT_DEPARTMENT_STR: "Select Department Visiting",
  SELECT_PERSON_STR: "Select Person Visiting",
  SELECT_PURPOSE_OF_VISIT_STR: "Select Purpose of Visit",
  PASSWORD_STR_S: "Password",
  REGISTER_ENTRY_STR: "Register Entry",
  SCAN_EXIT_STR: "Scan Exit",
  SCAN_CAR_LICENCE_STR: "Scan Car Licence",
  SCAN_ID_OR_DRIVER_LICENCE_STR: "Scan ID / Drivers License",
  NUMBER_OF_PEOPLE_STR: "Number of People",
  PURPOSE_OF_VISIT_STR: "Purpose of Visit",
  PERSON_VISITING_STR: "Person Visiting",
  SUBMIT_STR_S: "Submit",
  FORMS_STR: "Forms",
  NO_OF_FIELDS: "No.of Fields",
  ADDED_DATE: "Added Date",
  FLASH_MODE_STR: "Flash Mode",
  LOYALTYCARDS_STR: "Loyalty Cards",
  LOYALTY_CARD_STR: "Loyalty Card",
  FRONT_CARD_STR: "Front Card",
  BACK_CARD_STR: "Back Card",
  CARD_NAME_STR: "Card Name",
  TOTAL_POINTS_STR: "TOTAL POINTS",
  CYCLES_COMPLETED_STR: "Cycles Completed",
  GRACE_MONTH_AVAILABLE_STR: "Grace Month Avaiable",
  NO_STR: "No",
  CATEGORIES_STILL_TO_EARN_STR: "Categories Still to Earn",
  MARKET_VISIT_STR: "Market Visit",
  WELL_NESS_STR: "Wellness",
  CARD_FRONT_IMAGE_STR: "Card Front Image",
  CARD_BACK_IMAGE_STR: "Card Back Image",
  UPLOAD_STR: "Upload",
  UPLOAD_A_PHOTO_STR: "Upload a Photo",
  UPLOAD_A_FILE_STR: "Upload a File",
  FLIP_IMAGE: "Flip Image",
  UPDATE_STR: "Update",
  UPDATE_CARD_STR: "Update",
  DELETE_CARD_STR: "Delete",
  POINTS_BY_MONTH_STR: "Points by Month",
  JAN_STR: "Jan",
  FEB_STR: "Feb",
  MAR_STR: "Mar",
  APRL_STR: "Apr",
  MAY_STR: "May",
  JUNE_STR: "Jun",
  JULY_STR: "Jul",
  AUG_STR: "Agu",
  SEP_STR: "Sep",
  OCT_STR: "Oct",
  NOV_STR: "Nov",
  DEC_STR: "Dec",
  
}
