const Constantimages = {
  logo: require('../assets/images/logo.png'),
  close_icon: require('../assets/images/close.png'),
  search_icon: require('../assets/images/search.png'),
  back_icon: require('../assets/images/back.png'),
  hidepassword_toggle_icon: require('../assets/images/hide.png'),
  visiblepassword_toggle_icon: require('../assets/images/visible.png'),
  mail_icon: require('../assets/images/email.png'),
  lock_icon: require('../assets/images/lock.png'),
  background_image: require('../assets/images/bg.jpg'),
  logo_white: require('../assets/images/white_logo.png'),
  location_checkin_icon: require('../assets/images/add_location.png'),
  more_icon: require('../assets/images/more.png'),
  employee_icon: require('../assets/images/employee.png'),
  profile_icon: require('../assets/images/profile.png'),
  home_icon: require('../assets/images/home.png'),
  send_icon: require('../assets/images/send.png'),
  menu_icon: require('../assets/images/menu.png'),
  favrite_icon: require('../assets/images/favorite.png'),
  sendup_icon: require('../assets/images/sendup.png'),
  edit_icon: require('../assets/images/edit.png'),
  blackcircle_icon: require('../assets/images/blackcircle.png'),
  redcircle_icon: require('../assets/images/redcircle.png'),
  bluecircle_icon: require('../assets/images/bluecircle.png'),
  location2_icon: require('../assets/images/location2.jpg'),
  checked_icon: require('../assets/images/checked.png'),
  warning_icon: require('../assets/images/warning.png'),
  star_icon: require('../assets/images/star.png'),
  notification_icon: require('../assets/images/notification.png'),
  block_icon: require('../assets/images/block2.png'),
  review_icon: require('../assets/images/rating.png'),
  viewmore_icon: require('../assets/images/viewmore.png'),
  warning_icon: require('../assets/images/warning.png'),
  arrow_right_icon: require('../assets/images/arrow_right.png'),
  arrow_down_icon: require('../assets/images/arrow_down.png'),
  accesscontrol_icon: require('../assets/images/accesscontrol.png'),
  fillcheck_icon: require('../assets/images/fillcheck.png'),
  date_icon: require('../assets/images/date.png'),
  logout_icon: require('../assets/images/logout.png'),
  favoritefill_icon: require('../assets/images/favoritefill.png'),
  user_profile_icon: require('../assets/images/user_profile.png'),
  drop_icon: require('../assets/images/drop.png'),
  tick_icon:require('../assets/images/tick.png'),
  form_icon:require('../assets/images/form.png'),
  uncheck_icon:require('../assets/images/uncheck.png'),
  noimage_icon:require('../assets/images/noimage.png'),
  radiochecked_icon:require('../assets/images/radiochecked.png'),
  checked_box_icon:require('../assets/images/checked_box.png'),
  unchecked_box_icon:require('../assets/images/unchecked_box.png'),
  fastforword_icon:require('../assets/images/fastforword.png'),
  add_icon:require('../assets/images/add.png'),
  loyalty_icon:require('../assets/images/loyalty.png'),
  wellness_icon:require('../assets/images/wellness.png'),
  marketvisit_icon:require('../assets/images/marketvisit.png'),
  noimageavailable_icon:require('../assets/images/noimageavailable.png'),
  cloud_upload_icon:require('../assets/images/cloud.png'),
}
export default Constantimages;
